name: Efekta – Growth Marketing and Lean Innovation for the Internet Era
markdown: redcarpet
pygments: true
permalink: pretty

navigation:
- text: Growth Marketing
  url: /#growthmktg
- text: Lean Innovation
  url: /#innovation
- text: Customer Development
  url: /#custdev
- text: Who We Are
  url: /#us
- text: Contact Us
  url: /#contact
